package browser.dom

resource node {
  get_text() -> string
  set_text(value: string)
  append_child(child: node)
  remove()
}

resource document {
  create_element(tag: string) -> node
  body() -> node
}